services:
  - type: web
    name: voice-messenger
    plan: free
    env: python
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
